apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  namespace: app
  labels: 
    name: app-deploy
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: app
      type: netapi
  template:
    metadata:
      name: app-pod
      namespace: app
      labels:
        name: app
        type: netapi
    spec:
      containers:
      - name: app-api
        image: camjor/net-sql-camjor:v1.0
        ports:
          - containerPort: 5000
        env:
          - name: ConnectionStrings__SQLServerConnection
            value: Data Source=mssql-service; Initial Catalog=InmuebleDB; User Id=sa;password=pechoche12J*;TrustServerCertificate=True

